[workspace]
resolver = "2"
members = [
    "otd-core",
    "otd-cli",
    "otd-viewer",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Intermac"]
license = "MIT"

[profile.release]
lto = true
strip = true
